#!/bin/sh
# Regenerate or verify the benchmark corpus under tests/bench/.
#
# The corpus is checked in and fixed. A benchmark over whatever files happen to
# be present measures a different thing on every machine, so the members are
# data, not a view of src/. This script is the record of how they were made, so
# the corpus can be rebuilt and reviewed rather than trusted.
#
# The code members are drawn from pitch's own R7RS sources at a pinned
# revision, read with `git show` rather than from the working tree. Editing
# src/pitch/ therefore cannot move the corpus, and rerunning this script
# reproduces the checked-in bytes. Changing CODE_REV is a deliberate act that
# invalidates every recorded baseline.
#
# The data-dense member is generated here in full: a handful of very large
# quoted data forms, in the shape of a generated Unicode table. It is
# deterministic -- a fixed linear congruential sequence, no clock, no locale --
# so it rebuilds byte for byte.
#
# usage:
#   tools/generate-bench-corpus.sh            rewrite tests/bench/
#   tools/generate-bench-corpus.sh --verify   rebuild into a temp dir and diff

set -e

CODE_REV=4ad63ecbea6e9eb8a6bfed1a5c44328a7eef16fd

# The code members are a size ladder: the same unit of hand-written source
# repeated 1, 4 and 10 times. Composition is therefore identical across the
# three, and the only variable is file size -- which is what makes the
# largest-to-smallest per-line ratio a measurement of a term that grows with
# the document rather than a measurement of which modules happen to be in
# which member. A ladder built from different files measures their contents.
UNIT_PARTS="src/pitch/cst.sld src/pitch/table.sld"
SMALL_COPIES=1
MEDIUM_COPIES=4
LARGE_COPIES=11

banner() {
  printf ';; -*- mode: scheme; coding: utf-8 -*-\n'
  printf ';; Benchmark corpus member: hand-written code, %s copies of the unit.\n' "$1"
  printf ';;\n'
  printf ';; Not compiled, not installed, not part of the correctness suite.\n'
  printf ';; Assembled by tools/generate-bench-corpus.sh from pitch sources at\n'
  printf ';; %s. Do not edit by hand.\n' "$CODE_REV"
  printf '\n'
}

# Each copy is renamed so the member reads as a plausible source file rather
# than as the same library defined ten times. The formatter never resolves a
# library name, so this affects legibility only.
assemble_code() {
  out=$1
  copies=$2
  banner "$copies" > "$out"
  i=0
  while [ "$i" -lt "$copies" ]; do
    for part in $UNIT_PARTS; do
      printf ';; ---- %s, copy %d ----\n\n' "$part" "$i" >> "$out"
      git show "$CODE_REV:$part" \
        | sed "s/(pitch \\([a-z]*\\))/(bench \\1-$i)/g" >> "$out"
      printf '\n' >> "$out"
    done
    i=$((i + 1))
  done
}

# A handful of very large forms rather than many small ones. This is the shape
# that discriminates a per-form superlinearity from general per-line overhead,
# so the element counts are large and the form count is deliberately tiny.
generate_data() {
  out=$1
  awk 'BEGIN {
    split("Lu Ll Lt Lm Lo Mn Mc Nd Nl", CATS, " ")
    split("latin greek cyrillic capital small letter with acute grave sign symbol", WORDS, " ")
    seed = 20260901

    printf ";; -*- mode: scheme; coding: utf-8 -*-\n"
    printf ";; Benchmark corpus member: data-dense.\n"
    printf ";;\n"
    printf ";; Five very large quoted data forms in the shape of a generated\n"
    printf ";; Unicode table. Generated by tools/generate-bench-corpus.sh from a\n"
    printf ";; fixed seed; do not edit by hand.\n\n"

    printf "(define general-category-index\n  '\''#("
    emit_ints(7000, 8)
    printf "))\n\n"

    printf "(define code-point-ranges\n  '\''("
    emit_ranges(1800, 4)
    printf "))\n\n"

    printf "(define character-names\n  '\''("
    emit_named(1500, 3)
    printf "))\n\n"

    printf "(define simple-case-folding\n  '\''#("
    emit_pairs(2000, 5)
    printf "))\n\n"

    printf "(define decomposition-strings\n  '\''#("
    emit_strings(960, 4)
    printf "))\n"
  }

  function nextrand() {
    seed = (seed * 1103515245 + 12345) % 2147483648
    return seed
  }
  function pick(n) { return nextrand() % n }

  function emit_ints(n, per,   i) {
    for (i = 0; i < n; i++) {
      if (i % per == 0) printf "\n    "
      printf "%d ", pick(30)
    }
  }
  function emit_ranges(n, per,   i, lo, hi) {
    for (i = 0; i < n; i++) {
      if (i % per == 0) printf "\n    "
      lo = i * 17 + pick(11)
      hi = lo + pick(64)
      printf "(#x%X #x%X . %s) ", lo, hi, CATS[pick(9) + 1]
    }
  }
  function emit_named(n, per,   i) {
    for (i = 0; i < n; i++) {
      if (i % per == 0) printf "\n    "
      printf "(\"%s-%s-%04d\" . #x%04X) ", WORDS[pick(12) + 1], WORDS[pick(12) + 1], i, i * 7 + 32
    }
  }
  function emit_pairs(n, per,   i) {
    for (i = 0; i < n; i++) {
      if (i % per == 0) printf "\n    "
      printf "(#x%04X . #x%04X) ", i * 3 + 65, i * 3 + 97
    }
  }
  function emit_strings(n, per,   i) {
    for (i = 0; i < n; i++) {
      if (i % per == 0) printf "\n    "
      printf "\"\\x%04X;\\x%04X;\" ", i + 768, i + 800
    }
  }' | sed 's/ *$//' > "$out"
}

write_corpus() {
  dir=$1
  mkdir -p "$dir"
  assemble_code "$dir/code-small.scm"  "$SMALL_COPIES"
  assemble_code "$dir/code-medium.scm" "$MEDIUM_COPIES"
  assemble_code "$dir/code-large.scm"  "$LARGE_COPIES"
  generate_data "$dir/data-large.scm"
}

if [ "$1" = "--verify" ]; then
  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' EXIT HUP INT TERM
  write_corpus "$tmp"
  status=0
  for member in code-small code-medium code-large data-large; do
    if cmp -s "tests/bench/$member.scm" "$tmp/$member.scm"; then
      echo "ok       tests/bench/$member.scm"
    else
      echo "DRIFTED  tests/bench/$member.scm"
      status=1
    fi
  done
  exit $status
fi

write_corpus tests/bench
for member in code-small code-medium code-large data-large; do
  printf '%8d  tests/bench/%s.scm\n' "$(wc -l < "tests/bench/$member.scm")" "$member"
done
